// frontend/react/src/components/TodoList/TodoListItems.tsx
import { TodoListItem } from "./TodoListItem.tsx";
import { use } from "react";
import { TodosContext } from "../../store/todos-context.tsx";
import { NewTodo } from "./NewTodo.tsx";

export function TodoListItems() {
  const { todos } = use(TodosContext);
  if (!todos?.total) {
    return (
      <div className="flex flex-col gap-4">
        <h2>No records found, please add one.</h2>
        <NewTodo></NewTodo>
      </div>
    );
  }
  return (
    <>
      <div className="flex flex-row gap-2">
        <span className="text-stone-500">Total:</span>
        <span>{todos.total}</span>
      </div>
      {todos.data.map((todo, i) => (
        <TodoListItem key={todo.id} item={todo} index={i} />
      ))}
    </>
  );
}

// frontend/vue/src/components/Todo/TodoListItems.vue
<script lang="ts">
import { defineComponent } from 'vue';
import TodoListItem from './TodoListItem.vue';
import { useTodoStore } from "../../store/todo.store.ts";

export default defineComponent({
  name: "TodoListItems",
  components: { TodoListItem },
  computed: {
    todos: () => {
      const store = useTodoStore();
      return store.todos;
    }
  },
});
</script>

<template>
  <div v-if="!todos?.total" class="flex flex-col gap-4">
    <h2>No records found, please add one.</h2>
    <!--    todo add a condition on has any record to show the option below-->
    <!--    <NewTodo></NewTodo>-->
  </div>
  <div v-else>
    <div class="flex flex-row gap-2">
      <span class="text-stone-500">Total:</span>
      <span>{{ todos?.total }}</span>
    </div>
    <TodoListItem v-for="(todo, index) in todos?.data" :index="index" :todo="todo"></TodoListItem>
  </div>
</template>

<style scoped>

</style>
