// frontend/vue/src/components/Todo/TodoList.vue
<script lang="ts">
import { defineComponent } from 'vue';
import TodoListItems from "./TodoListItems.vue";
import SortingButton from "./SortingButton.vue";
import { useTodoStore } from "../../store/todo.store.ts";

export default defineComponent({
  name: "TodoList",
  components: { TodoListItems, SortingButton },
  setup: () => {
    function handleCancel() {

    }

    function handleTextChange(e: Event) {

    }

    const todoState = useTodoStore
    return {
      todoState,
      handleTextChange,
      handleCancel,
    };
  }
});
</script>

<template>

  <div class="flex flex-col gap-2">
<!--    <NewTodo v-if="!todoState.hasAnyRecord"></NewTodo>-->
    <div>
      <div class="flex flex-col my-2 py-4 gap-4 border-b border-t border-stone-700">
        <div class="flex flex-row gap-2">
          <label for="search-text" class="text-xl text-stone-500">
            Search
          </label>
          <input
              id="search-text"
              type="text"
              name="search-text"
              class="px-1 border rounded text-sm"
              @change={handleTextChange}
          />
        </div>
        <div class="flex flex-row gap-2 items-center">
          <span class="text-stone-500">
            Order by
          </span>
          <SortingButton sorting="todoState.sorting" value="date_created">Date created</SortingButton>
          <SortingButton sorting="todoState.sorting" value="content">Content</SortingButton>
          <SortingButton sorting="todoState.sorting" value="order">Order</SortingButton>
        </div>
      </div>
      <TodoListItems></TodoListItems>
    </div>
  </div>
</template>

<style scoped>

</style>

// frontend/react/src/components/TodoList.tsx
import { use } from "react";
import { TodoListItem } from "./TodoListItem";
import { TodosContext } from "../store/todos-context.tsx";
import { NewTodo } from "./NewTodo.tsx";
import { Button } from "./Button.tsx";
import { SortingButton } from "./SortingButton.tsx";

export function TodoList() {
  const { todos, error, loading, todoToUpdate, unselectTodo, sort, sorting } = use(TodosContext);

  if (loading) {
    return <h2>Loading...</h2>;
  }
  if (error) {
    return <h2>Error: {error}</h2>;
  }
  if (!todos?.total) {
    return (
      <div className="flex flex-col gap-4">
        <h2>No records found, please add one.</h2>
        <NewTodo></NewTodo>
      </div>
    );
  }
  function handleCancel() {
    unselectTodo();
  }
  function handleSort(sortOn: "date_created" | "content") {
    let direction: "asc" | "desc" = "asc";
    if (sorting.sort === sortOn) {
      direction = sorting.direction === "asc" ? "desc" : "asc";
    }
    sort({
      direction, sort: sortOn,
    })
  }

  if (todoToUpdate) {
    return <NewTodo saveButtonLabel="Update" todo={todoToUpdate} onCancel={handleCancel}></NewTodo>
  }
  return (
    <>
      <div className="flex flex-col gap-2">
        <div className="flex flex-row gap-2 items-center">
          Order by:
          <SortingButton value="date_created" onSort={() => handleSort("date_created")} currentSorting={sorting}>Date created</SortingButton>
          <SortingButton value="content" onSort={() => handleSort("content")} currentSorting={sorting}>Content</SortingButton>
        </div>
        {todos.data.map((todo) => (
          <TodoListItem key={todo.id} item={todo} />
        ))}
      </div>
      <NewTodo></NewTodo>
    </>
  );
}
